---
title: "Retail Analytics"
output: word_document
---

```{r setup}

# Importing data
library(readxl)
transaction_data=read_excel("C:/Users/Dell/Desktop/pro/transaction_data.xlsx")
```
```{r}

#Checking Structure of data
head(transaction_data)
dim(transaction_data)
str(transaction_data)
transaction_data$DATE=as.Date(transaction_data$DATE, origin="1899-12-30")
```
```{r}
#Summarizing Data
head(transaction_data)
summary(transaction_data)
```
```{r}
#Adding Month column
library(dplyr)
library(lubridate)
transaction_data=transaction_data %>%
  mutate(MONTH=month(DATE))
head(transaction_data)
```
```{r}
#Adding column Pack_size to data
library(dplyr)
library(purrr)
library(stringr)
transaction_data=transaction_data %>%
  mutate(PACK_SIZE = readr::parse_number(as.character(PROD_NAME)))
head(transaction_data)
summary(transaction_data)
```
```{r}
#Finding and excluding outliers
which(transaction_data$PROD_QTY==200)
transaction_data=transaction_data[-(69763:69764),]
dim(transaction_data)
str(transaction_data)
```
```{r}
#Finding which preferred pack size
hist(transaction_data$PACK_SIZE)
y=table(transaction_data$PACK_SIZE)
names(y)[which(y==max(y))]
```
```{r}
#To see Correlation between variables
library(corrplot)
correlation=cor(transaction_data[,-c(1,6)])
corrplot(correlation, method="color", addCoef.col= "red",tl.col="black")
```
```{r}
#Exploring Consumer data
library(readr)
library(dplyr)
Customer_data=read_csv("C:/Users/Dell/Desktop/pro/purchase_data.csv")
head(Customer_data)
dim(Customer_data)
table(Customer_data$LIFESTAGE)
table(Customer_data$PREMIUM_CUSTOMER)
table(Customer_data$LIFESTAGE,Customer_data$PREMIUM_CUSTOMER)
info=data.frame(table(Customer_data$LIFESTAGE,Customer_data$PREMIUM_CUSTOMER))
colnames(info)=c("Life stage","Premium customer","Freq")

library(ggplot2)
ggplot(data =info, aes(x=`Life stage`, y=Freq, fill=`Premium customer`)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75)+
  labs(x="\n Life Stage", y="Frequency\n", title="\nDistribution of     Customers\n")+
  theme(axis.text.x = element_text(angle =65, hjust = 1))

#Combining transaction and customer data set.
trans_data=transaction_data %>%
     group_by(LYLTY_CARD_NBR) %>%
     summarize(Prod_qty=sum(PROD_QTY),
               Tot_sales=sum(TOT_SALES),
               Store_Nbr=mean(STORE_NBR),
               Pack_size=sum(PACK_SIZE));

head(trans_data)
dim(trans_data)

comb_data=data.frame(inner_join(trans_data,Customer_data,by="LYLTY_CARD_NBR"))
head(comb_data)
dim(comb_data)
summary(comb_data)
library(ggplot2)
ggplot(data =comb_data, aes(x=`LIFESTAGE`, y=`Tot_sales`, fill=`PREMIUM_CUSTOMER`)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75)+
  labs(x="\n Life Stage", y="Total Sales\n", title="\n Customers contributing to total_sales\n")+theme(axis.text.x = element_text(angle =65, hjust = 1))

```
```{r}
knitr::opts_chunk$set(warning=FALSE,message=FALSE)

# Cleaning and Analyzing Product name column
name=data.frame(table((transaction_data$PROD_NAME)))
library(wordcloud2)
library(RColorBrewer)
library(tm)
getwd()
library(readr)
write_tsv(name, file = "name.txt")
text=readLines(file.choose())
docs=Corpus(VectorSource(text))
library(dplyr)
docs=docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)

docs=tm_map(docs, content_transformer(tolower))
docs=tm_map(docs, removeWords, stopwords("english"))

dtm=TermDocumentMatrix(docs) 
matrix=as.matrix(dtm) 
words=sort(rowSums(matrix),decreasing=TRUE) 
df=data.frame(word = names(words),freq=words)
set.seed(678)
wordcloud2(data=df,size=1.2, color='random-dark')

```
```{r}
#Checking total sales
total_sales=sum(transaction_data$TOT_SALES);total_sales
```
```{r}
#Checking Sales by Store number
d_table=data.frame(sort(table(transaction_data$STORE_NBR)))
f=d_table$Freq
d_table %>% mutate(cont_per=(f/sum(f))*100)


```
```{r}
#Sorting number of Products sold month-wise

data=transaction_data %>%
  group_by(DATE) %>%
  summarize(tot_sales=sum(TOT_SALES)) %>%
  mutate(month=month(DATE))

head(data)
dim(data)

date=data$DATE
date_range=seq(min(date), max(date), by = 1) 
date_range[!date_range %in% date] 

```
```{r}
##Visualising the total sales
library(readr)
library(lubridate)
library(scales)
library(ggplot2)
ggplot(data, aes(x =DATE, y =tot_sales))+geom_line()+
  scale_x_date(labels=date_format("%d-%b-%y"),breaks = ("1 month"))
  
ggplot(data, aes(x =DATE, y =tot_sales))+geom_line()+
  scale_x_date(labels=date_format("%b-%y"),breaks=("15 days"))+
  facet_wrap(~month,scales = "free")
```
```{r}
## Decision tree 
level=ifelse(transaction_data$TOT_SALES<=7,"No","Yes")
dec_data=cbind(transaction_data[,-c(1,3,4,5,6,8)],level)
head(dec_data)
library(caTools)
set.seed(987)
sample=sample.split(dec_data, SplitRatio=0.8)
train=subset(dec_data, sample==TRUE)
test=subset(dec_data,sample==FALSE)
library(rpart)
tree=rpart(level~.,data=train,method = "class")
tree
```
```{r}
# Visualize the decision tree with rpart.plot
library(rpart.plot)
rpart.plot(tree,nn=TRUE)
Prediction1=predict(tree,newdata=test,type = 'class')
```
```{r}
knitr::opts_chunk$set(warning=FALSE,message=FALSE)
# Confusion matrix
library(caret)
library(e1071)
confusionMatrix(as.factor(Prediction1),as.factor(test$level))
```



